export const questions = [
    {question: 'Jak zapisać się na wizytę?', answer: "Na wizytę u stomatologa najlepiej zapisać się telefonicznie. Nasze asystentki stomatologiczne umówią Państwa na najbliższy wolny termin."},
    {question: 'Jakie są terminy wizyt?', answer: "Staramy się umawiać nowych pacjentów na najbliższe terminy."},
    {question: 'Czy wybielanie zębów jest bezpieczne?', answer: "Wybielanie zębówpod kontrola dentysty jest bezpieczne. Obecnie stosowane preparaty są zupełnie nieszkodliwe dla szkliwa. Specjalistyczne badania wykazały, że preparaty wybielające nie zwiększają podatności na próchnicę."},
    {question: 'Czym jest implant?', answer: "Implant to specjalnie wykonany, zwykle z tytanu, sztuczny korzeń zęba, zastępujący usunięty lub utracony wcześniej korzeń naturalny. Implant stomatologiczny umożliwia zamocowanie nowej korony zębowej na miejscu utraconego zęba. Stomatologiczny implant zębowy umieszczany jest w kości wyrostka zębowego poprzez wkręcenie."},
    {question: 'Czym jest aligner?', answer: "Aligner to przezroczysty aparat ortodontyczny w formie silikonowych nakładek na zęby. To nie tylko komfortowa alternatywa dla tradycyjnych aparatów, ale przede wszystkim prawdziwa innowacja w dziedzinie korekty ustawienia zębów i wyglądu uśmiechu. Dzięki technologii obrazowania 3D każdy pacjent otrzymuje plan prostowania zębów oraz wizualizację od pozycji początkowej do pożądanej."},
    {question: 'Jak wygląda aligner?', answer: "Aligner to przezroczysty aparat ortodontyczny w formie silikonowych nakładek na zęby. To nie tylko komfortowa alternatywa dla tradycyjnych aparatów, ale przede wszystkim prawdziwa innowacja w dziedzinie korekty ustawienia zębów i wyglądu uśmiechu. Dzięki technologii obrazowania 3D każdy pacjent otrzymuje plan prostowania zębów oraz wizualizację od pozycji początkowej do pożądanej."},
    {question: 'Czy stosowanie alignerów jest bezpieczne?', answer: "Nie. Lekki dyskomfort odczuwany przez część pacjentów występuje na samym początku leczenia, w większości przypadków ustępuje po kilku dniach."},
    {question: 'Czy mogę leczyć wadę zgryzu w IDENTI?', answer: "W naszej ofercie posiadamy autorskie nakładki, które dostępne są w każdym z naszych gabinetów. Po konsultacji z naszym ortodontą opracowany zostaje plan prostowania zębów, a następnie nakładki możesz odebrać w naszym gabinecie lub zostaną wysłane do Ciebie pocztą."},
]